name: generate-verifiable-builds
on:
  workflow_dispatch:
  push:
    branches:
      - production
      - develop

jobs:
  generate-verifiable-autocrat:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-verifiable-build@v0
        with:
          program: autocrat
          anchor-version: '0.29.0'
          solana-cli-version: '1.17.16'
      - run: 'git pull --rebase'
      - run: cp target/deploy/autocrat.so ./verifiable-builds
      - name: Commit verifiable build back to mainline
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: 'Update autocrat verifiable build'
  generate-verifiable-vault:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-verifiable-build@v0
        with:
          program: conditional_vault
          anchor-version: '0.29.0'
          solana-cli-version: '1.17.16'
      - run: 'git pull --rebase'
      - run: cp target/deploy/conditional_vault.so ./verifiable-builds
      - name: Commit verifiable build back to mainline
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: 'Update conditional_vault verifiable build'
  generate-verifiable-amm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-verifiable-build@v0
        with:
          program: amm
          anchor-version: '0.29.0'
          solana-cli-version: '1.17.16'
      - run: 'git pull --rebase'
      - run: cp target/deploy/amm.so ./verifiable-builds
      - name: Commit verifiable build back to mainline
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: 'Update amm verifiable build'
