name: Verify Build

on:
  workflow_dispatch:
    inputs:
      program_name:
        description: 'Program name'
        required: true
        type: string
      program_id:
        description: 'Program ID'
        required: true
        type: string
      anchor-version:
        description: 'Anchor version'
        required: true
        default: '0.29.0'
      solana-cli-version:
        description: 'Solana CLI version'
        required: true
        default: '1.17.16'

jobs:
  verify-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: ${{ inputs.anchor-version }}
          solana-cli-version: ${{ inputs.solana-cli-version }}
      - name: Cache Cargo registry + index
        uses: actions/cache@v2
        id: cache-cargo-registry
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0001-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Solana Verify
        uses: actions/cache@v2
        id: cache-solana-verify
        with:
          path: |
            ~/.cargo/bin/solana-verify
          key: cargo-${{ runner.os }}-solana-verify
      - run: cargo install solana-verify
        if: steps.cache-solana-verify.outputs.cache-hit != 'true'
        shell: bash
      - name: Verify build
        run: |
          solana-verify verify-from-repo -um --program-id ${{ inputs.program_id }} https://github.com/${{ github.repository }}
